version: "3.8"
services:
  backend-dev:
    image: cosmtrek/air
    working_dir: /home/app
    ports:
      - 3000:3000
    volumes:
      - ./backend/:/home/app
    environment:
      - MYSQL_CONNECTION_STRING=root:password@(mysql_db)/tbd?parseTime=true
      - PORT=3000
    depends_on:
      - db

  db:
    image: mysql
    container_name: "mysql_db"
    restart: always
    environment:
      MYSQL_DATABASE: tbd
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
    driver: local
